version: "3"

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - spring-example-db

  spring-example-db:
    image: postgres:latest
    container_name: spring-example-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: springexampledb
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: